# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/voltimetro/Sintesis_/Sintesis_.runs/synth_1/Voltimetro.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/voltimetro/Sintesis_/Sintesis_.cache/wt [current_project]
set_property parent.project_path C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/voltimetro/Sintesis_/Sintesis_.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/voltimetro/Sintesis_/Sintesis_.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/BCD_counter/Fuentes/BCD_counter.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/c33k/Fuentes/c33k.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/cOnes/Fuentes/cOnes.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/carac_rom/Fuentes/carac_rom.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/comp_Nb/Fuentes/comp_Nb.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/cont_bin_gen/Fuentes/cont_bin_gen.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/ffd/Fuentes/ffd.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/hsync/Fuentes/hsync.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/mux/Fuentes/mux.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/mux_color/Fuentes/mux_color.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/mux_selector/Fuentes/mux_selector.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/reg_Nb/Fuentes/reg_Nb.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/registro/Fuentes/registro.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/vga_controller/Fuentes/vga_controller.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/vsync/Fuentes/vsync.vhd
  C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Codigos/voltimetro/Fuentes/Voltimetro.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Arty_A7_35.xdc
set_property used_in_implementation false [get_files C:/Users/Alpha/Documents/GitHub/TP_Final_ED1/bloques_codigo/Arty_A7_35.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Voltimetro -part xc7a35ticsg324-1L
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Voltimetro.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Voltimetro_utilization_synth.rpt -pb Voltimetro_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
